# Generated by Django 3.2.5 on 2021-08-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
    ]
