# Generated by Django 3.2.5 on 2021-08-14 12:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20210812_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(default='Dodaj artykul...'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.TextField(default='Stworz krotki opis...', max_length=300),
        ),
    ]
