# Generated by Django 3.2.5 on 2021-08-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210814_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_highlited',
            field=models.NullBooleanField(default=False),
        ),
    ]
