# Generated by Django 3.2.5 on 2021-08-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_post_pictute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_pictute',
            new_name='post_picture',
        ),
    ]
