# Generated by Django 3.2.5 on 2021-08-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_post_pictute_post_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_picture_admin',
            field=models.ImageField(blank=True, null=True, upload_to='images/admin'),
        ),
    ]
